# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XDCExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # pod 'XDC', :path => '../XDC'
 # pod 'GenericJSON', '~> 2.0.0'
 # pod 'BigInt', '~> 5.2.0'
 # pod 'secp256k1.swift', '~> 0.1.0'
  pod 'iOSDropDown', '~> 0.3'
  pod 'XDC3Swift', '~>1.3.0 '

  # Pods for XDCExample

end
